### PR TITLE
Update deploy helper tooling

### PR DESCRIPTION
**Pull request by andrewtruong**
This tool takes images from the [W&B dockerhub](https://hub.docker.com/?namespace=wandb) and populates a jobs page.  The intended target is [W&B's public jobs page](https://wandb.ai/wandb/jobs/jobs), but this can be used to create any jobs page (just change the entity).

Users have control over what jobs appear in the registry and their presentation (name, description) via the top level `registry.yaml` file.

You can also provide sample `config.yml` files in each job's `configs/` dir.  Each config will produce a unique run that the end user can `Clone from...` in the UI.

### CODE REVIEW

**Review by jlzhao27 — COMMENTED** [review]
I'm fine merging this as is but we should move the CI steps out of the notebooks imo

**Comment by andrewtruong** [comment]
> I'm fine merging this as is but we should move the CI steps out of the notebooks imo

Yeah we're gonna see if we can do the notebook stuff in CI.

**Comment by jlzhao27** [comment]
I would vote we don't do that, it feels pretty weird to depend on jupyter in CI, it introduces a lot of extra complexities that I don't think is good practice for CI. e.g. instead running the native python interpreter, you are running it through jupyter which could make debugging a lot harder. There is also the issue of clearing the notebook outputs and diffing in PRs that makes it a nightmare

**Comment by andrewtruong** [comment]
I'm going to merge this as-is for now.

In a future PR, we'll replace the notebook with normal `.py` files and move this logic into CI.

**Pull request merged**
